export interface SaveForm20 {
  id: number;
  bondMaintenancePercentage: string;
  bondOtherPercentage: string;
  bondPaymentPercentage: string;
  bondPerformancePercentage: string;
  bondRetentionPercentage: string;
  bondTenderPercentage: string;
  paymentRetentionAmountPercent: string;
  businessUnitId: number | null;
  approximateValue: number | null;
  profitMargin: number | null;
  periodUnit: string;
  period: number | null;
  periodDetail: string;
  maintenanceDefectUnit: string;
  maintenanceDefectPeriod: number | null;
  maintenanceDefectId: number | null;
  ContractPeriod: string;
  title: string;

  currencyId: number | null;
  tenderTypeId: number | null;
  clientFinanceStanding: string | null;
  splitValueId: number | null;
  countryId: number | null;
  bidTypeId: number | null;
  JvSplit: string;
  JvPartner: string;
  jvAgreementId: number | null;
  distributionComDir: string[];
  distributionDivComM: string[];
  distributionExeDir: string[];
  distributionFinDir: string[];
  distributionCE: string[];
  distributionDir: string[];
  distributionGenC: string[];
  distributionInsMgr: string[];
  distributionProc: string[];
  distributionRiskOpp: string[];
  distributionLambeth: string[];
  distributionHSEQ: string[];
  businessUnitCode: string;
  distributionBidMgr: string[];
  Status: string;

  //page 2 
  contractTypeId : number | null;
  contractFormRiskCode: string;
  contractFormDescription: string;
   
  contractDamageRateRemark: string;
  contractLiabilityLimit: string;
  contractDamageRiskCode: string;

  contractMeasurementId : number | null;
  contractMeasurementRiskCode : string;

  contractFluctuationId : number | null;
  contractFluctuationRiskCode : string;
  contractIsAdversePhyiscal : string;
  contractIsTimeExtension: string;
  contractIsTimeExtensionValue: string;
  contractClausesRiskCode: string;
  contractUnusualConditions : string;
  contractUnusualRiskCode: string;
  contractDesignResponsibility: string;
  contractDesignRiskCode: string;
  contractBIMRequired: string;
  contractBIMRiskCode: string;
  contractDFMARequired: string;
  contractDFMARiskCode: string;


  Planner: string;
  Location: string;
  TenderNo: string;
  Estimator: string;

  BidManager: string;
  clientName: string;
  Competitor: string;
  Description: string;
  ConsultantEM: string;
  BondOtherName: string;
  OtherIsPFIPPP: string;
  BondOtherRemark: string;
  isMarkingScheme: string;
  BondTenderRemark: string;
  ConsultantOthers: string;
  BondOtherRiskCode: string;
  BondPaymentRemark: string;
  PaymentPeriodUnit: string;
  BondOtherCallBasis: string;
  BondTenderRiskCode: string;
  CompetitorRiskCode: string;
  EvaluationCashFlow: string;
  EvaluationComments: string;
  BondOtherExpiryDate: string;
  BondPaymentRiskCode: string;
  BondRetentionRemark: string;
  BondTenderCallBasis: string;
  ConsultantArchitect: string;
 
  OtherPFIPPPRiskCode: string;
  PaymentCashRiskCode: string;
  BondPaymentCallBasis: string;
  BondTenderExpiryDate: string;
  ConsultantEMRiskCode: string;
  
  EvaluationIsCashFlow: string;
  OtherForeignCurrency: string;
  BondMaintenanceRemark: string;
  BondPaymentExpiryDate: string;
  BondPerformanceRemark: string;
  BondRetentionRiskCode: string;
  EvaluationCompetition: string;
  EvaluationPaymentTerm: string;
  EvaluationTimeAllowed: string;
  PaymentPeriodRiskCode: string;
  PaymentRetentionLimit: string;
  approximateValueRemark: string;
  BondRetentionCallBasis: string;
  ContractDamageRateUnit: string;
  
  
  OtherFinancingRequired: string;
  BondMaintenanceRiskCode: string;
  BondPerformanceRiskCode: string;
  BondRetentionExpiryDate: string;
 
  EvaluationBondGuarantee: string;
  EvaluationIsCompetition: string;
  EvaluationIsPaymentTerm: string;
  EvaluationIsTimeAllowed: string;
  BondMaintenanceCallBasis: string;
  BondPerformanceCallBasis: string;
  ConsultantCivilStructure: string;
  ConsultantOthersRiskCode: string;
  
  EvaluationSiteManagement: string;
  PaymentRetentionRiskCode: string;
  BondMaintenanceExpiryDate: string;
  BondPerformanceExpiryDate: string;
  EvaluationCompanyWorkload: string;
  EvaluationIsBondGuarantee: string;
  InsuranceShortFallInCover: string;
  ConsultantQuantitySurveyor: string;
  EvaluationConsultantRecord: string;
  EvaluationIsSiteManagement: string;
  ConsultantArchitectRiskCode: string;
  EvaluationContractCondition: string;
  EvaluationIsCompanyWorkload: string;
  InsuranceIsShortFallInCover: string;
  InsuranceOnerousRequirement: string;
  InsuranceProvidedByEmployer: string;
  InsuranceThirdPartyRiskCode: string;
  EvaluationIsConsultantRecord: string;
  OtherForeignCurrencyRiskCode: string;
  PaymentCertificationRiskCode: string;
  PaymentRetentionAmountRemark: string;
  EvaluationIsContractCondition: string;
  EvaluationValueExtendContract: string;
  InsuranceIsOnerousRequirement: string;
  InsuranceIsProvidedByEmployer: string;
  PaymentRetentionLimitRiskCode: string;
  OtherFinancingRequiredRiskCode: string;
  PaymentCertificationPeriodUnit: string;
  EvaluationClientFinancialStatus: string;
  EvaluationIsValueExtendContract: string;
  OtherPlantInvestmentRequirement: string;
  WarrantGuranteeOtherLiabilities: string;
  ConsultantCivilStructureRiskCode: string;
  EvaluationPlantEquipmentRequired: string;
  PaymentCertificationPeriodRemark: string;
  EvaluationHealthSafetyEnvironment: string;
  EvaluationIsClientFinancialStatus: string;
  InsuranceShortFallInCoverRiskCode: string;
  WarrantGuranteeIsOtherLiabilities: string;
  ConsultantQuantitySurveyorRiskCode: string;
  EvaluationIsPlantEquipmentRequired: string;
  EvaluationIsHealthSafetyEnvironment: string;
  InsuranceOnerousRequirementRiskCode: string;
  InsuranceProvidedByEmployerRiskCode: string;
  WarrantGuranteeCollateralWarranties: string;
  WarrantGuranteeIsCollateralWarranties: string;
  WarrantGuranteeParentCompanyGuarantee: string;
  EvaluationEstimatingDepartmentWorkload: string;
  OtherPlantInvestmnetRequirementRiskCode: string;
  WarrantGuranteeIsParentCompanyGuarantee: string;
  WarrantGuranteeOtherLiabilitiesRiskCode: string;
  WarrantGuranteeParentCompanyUnderTaking: string;
  EvaluationIsEstimatingDepartmentWorkload: string;
  WarrantGuranteeIsParentCompanyUnderTaking: string;
  WarrantGuranteeCollateralWarrantiesRiskCode: string;
  WarrantGuranteeParentCompanyGuaranteeRiskCode: string;
  WarrantGuranteeParentCompanyUnderTakingRiskCode: string;
  CEApproval: ApprovalInfo[];
  CMApproval: ApprovalInfo[];
  EDApproval: ApprovalInfo[];
  DirApproval: ApprovalInfo[];
  HoEApproval: ApprovalInfo[];
}

interface ApprovalInfo {
  Title: string;
  Comments: string;
  Decision: string;
  StaffNo: string;
  ApproverName: string;
}
