import { BusinessUnit } from './business-unit';
import { GammonEntity } from './gammon-entity';
import { Currency } from './currency-list';
import { MarketSector } from './market-sector-list';
import { PriorityLevel } from './priority-level-list';
import { TenderAttachment } from './tenderAttchemnt';
import { excomDecisionPriorityLevel } from './excomDecisionPriorityLevel';
import { RiskAssessmentCriteria } from './risk-assessment-criteria';

export interface TenderItem {
  id: number;
  division: string;
  tenderStatus: string;
  reportDate?: string | null;
  businessUnitId: number;
  isExternal: string;
  region: string;
  projectName: string | null;
  expectedTenderIssueDate: string;
  expectedTenderSubmissionDate: string;
  projectDuration: number | null;
  biddingGammonEntityId: number | null;
  projectDescription: string | null;
  customerName: string | null;
  marketSectorId: number | null;
  marketSectorVal: string;
  currencyId: number | null;
  estimatedTenderValue: number;
  estimatedTenderValueInHKD: number | null;
  isExternalMainContractor: string | null;
  isKeyCustomer: string;
  isKeySector: string;
  isJointVenture: string;
  foreseenBUCapacity: string;
  standardResponsePriorityLevelId: number | null;
  standardResponseHint: string | null;
  upgradeDowngradePriorityLevelId: number | null;
  upgradeDowngradeRationale: string | null;
  riskAssessmentCriteriaId: number;
  riskAssessmentLevel: string | null;
  riskAssessmentRationale: string | null;
  excomDecisionItem: string | null;
  excomDecisionPriorityLevelId: number | null;
  excomDecisionDate: string | null;
  excomDecisionNotes: string | null;
  winningCompetitor: string | null;
  marginLostPercentage: number | null;
  otherReasonsForLoss: string | null;
  additionalNote: string | null;
  changeSinceLastDecisionMade: boolean;
  form20Id: number | null;
  businessUnit: BusinessUnit;
  biddingGammonEntity: GammonEntity | null;
  marketSector: MarketSector | null;
  currency: Currency | null;
  standardResponsePriorityLevel: PriorityLevel | null;
  upgradeDowngradePriorityLevel: PriorityLevel | null;
  riskAssessmentCriteria: RiskAssessmentCriteria;
  excomDecisionPriorityLevel: excomDecisionPriorityLevel | null;
  tenderAttachments: TenderAttachment | null;
  tenderKeyDates: any | null;
  createdBy: string;
  createdOn: string;
  lastModifiedBy: string;
  lastModifiedOn: string;
  status: string;
}
